### ISSUE TITLE
JSON API for Categories, Products, Orders components etc

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#105]
Are there add api add-ons for mobile application?

**Comment by tobias-kuendig** [comment]
What exactly do you mean by that?

**Comment by HomaEEE** [comment]
json parsing of categories, products, and create order from mobile app

**Comment by tobias-kuendig** [comment]
Currently this is not available. I'm leaving this issue open in case someone has time to implement this.

**Comment by HomaEEE** [comment]
for example https://octobercms.com/plugin/ipricegroup-ocapiplugin plugin generate Restfull API

**Comment by chrisvidal** [comment]
I am thinking to work on this.
would you have specific requirements in mind?

**Comment by tobias-kuendig** [comment]
I do not have anything specific in mind - I didn't think this part through since it has rather low priority for our own needs.

I guess the bare minimum would be to have a `/mall/api/products` endpoint to list products that allows passing a filter via get params as well as a `/mall/api/products/{id}/{variant}` endpoint that returns all product information. 

Thinking about it, this becomes a very deep rabbit hole very fast. Providing half-baked solutions won't help anyone. So there have to be further endpoints for the `Cart`, `Login` and `Signup`, `Addresses` the whole `Checkout` process as well as `Discounts`, `ShippingMethods` and `Orders`.

This will be quite the task. Especially since there should be as little code duplication as possible.

What did you have in mind as a solution for this, @chrisvidal?

**Comment by chrisvidal** [comment]
my approach would be to provide everything required for a mobile app development based on the plugin.

Regarding the existing code, we would probably have to refactor some of it using the Repository pattern which I already used in one of my internal plugins.

**Comment by chrisvidal** [comment]
and most of the existing code in the current component would have to be refactored into Facade Manager. Basically, one model will give one Facade Manager

**Comment by tobias-kuendig** [comment]
A built-in JSON api will very likely never be part of this plugin, so I am closing this issue for now.
