### ISSUE TITLE
TotalsCalculator.php:19

### ISSUE THREAD

**Issue by Pascualsolutions** [OFFLINE-GmbH/oc-mall-plugin#1114]
Hello, after installation plugin and theme i have this error in log
Error: Interface "October\Contracts\Twig\CallsAnyMethod" not found in /home/pascual/Desktop/wintercmsTest/winterCMSSQliteTest/plugins/offline/mall/classes/totals/TotalsCalculator.php:19

Can u help pls.
Best regards Alex

**Comment by SamBrishes** [comment]
Hello,

thanks for your issue / report. Looks like you're using either WinterCMS, which is based on OctoberCMS v1.1.2 (as far as i know), or a deprecated OctoberCMS v2 version (less then v2.2). According to the path in your comment, probably the former one.

Mall dropped v1 support a long time ago, and requires at least OctoberCMS v2.2 (or OctoberCMS v3+).

I don't know how @tobias-kuendig sees the support for WinterCMS, but I think that the official Mall Extension should not support 2 different systems, especially if they will continue to differ in the future. Since the only [WinterCMS port I know of was archived](https://github.com/search?q=mall%20wintercms&type=repositories) end of last year, you can either upgrade to OctoberCMS or develop your own fork.

You can of course just add the missing interface yourself, but keep in mind that there may be many similar (or different) problems in other places too.

Sincerely,\
Sam.

**References**
* [October\Contracts\Twig\CallsAnyMethod](https://github.com/octobercms/library/commit/c2c90eebffbfbd14ea8129b312943c7a2d990357) has been introduced in v2.2.0

**Comment by mjauvin** [comment]
Branch v2 is compatible with WinterCMS v1.2+

**Comment by mjauvin** [comment]
The error is happening because you are not using the correct branch (v2}.

**Comment by mjauvin** [comment]
Please use this command to install the proper version:

`comppser require offline/oc-mall-plugin v2.x-dev`

**Comment by SamBrishes** [comment]
Thanks for the hint, didn't know that v2 pays attention to WinterCMS. Still, I don't know if the branch is still actively maintained besides a few community commits, but it definitively misses many changes that have already been made in v3 and will arrive in the near future.

**Comment by tobias-kuendig** [comment]
@SamBrishes the v2 branch is kept to remain compatible with Winter CMS and older October CMS versions. It does only receive security fixes and fixes provided by the community.

@Pascualsolutions @mjauvin's solution should work in this case. Thank you for providing it, @mjauvin!

**Comment by Pascualsolutions** [comment]
Thank you very much for your help and the information. The plugin is now working without any errors. I also installed the Mall theme which I still haven't managed to configure, but it might be necessary to install an older version there too. Thank you once again.
Best regards, Alex.
