### ISSUE TITLE
Missing recordsPerPage and showSearch customergroups/config_relation.yaml

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1131]
Hello.
Can we please have in `customergroups/config_relation.yaml`
`recordsPerPage `and `showSearch ` in the `view `option?
Thanks

**Comment by tobias-kuendig** [comment]
@dathwa Not sure what these settings would do? The view is a form view, so no pagination or search is required. The manage key already has the search/view. Please provide more details why this change is needed.

Also, feel free to create PRs with these requests since it is almost as much work for you but considerably less work for the plugin maintainers, thank you!
