### ISSUE TITLE
Mall with Multisite ?

### ISSUE THREAD

**Issue by zimbar** [OFFLINE-GmbH/oc-mall-plugin#1153]
Hy

is the plugin designed to work in multisite ? if yes, How ?

Thanks

**Comment by zimbar** [comment]
Hy,

NO response ?

**Comment by tobias-kuendig** [comment]
There is currently no explicit support for the Multisite feature. This means it probably won't work, but it is completely untested.

If someone wants to step up and provide a merge request with the required changes we will happiliy merge it!

**Comment by tobias-kuendig** [comment]
Everything seems to be working good enough! We still use RainLab.Translate to translate the attributes and not per-site copies of the models, but this should not matter in the end. 

You can create sites for multiple languages and translate all data.

Just be careful when using richtext fields in Firefox. It can happen that you override the translations because of this bug:
https://github.com/froala/wysiwyg-editor/issues/2655
