### ISSUE TITLE
[Enhancement] Ability to send Customer Data when processing stripe payments

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#154]
I'm not sure if you thought about it yet, but is there a way to send the customer data you collect with the stripe payment info? It would be lot easier to dispute charges (if any) when you have the data in their system.

**Comment by artistro08** [comment]
Additionally, you would be creating a customer in stripe's backend.

**Comment by tobias-kuendig** [comment]
This should be possible by extending the [stripe payment provider](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/payments/Stripe.php).

I'm leaving this issue open since this would be a great addition to the default feature set.

**Comment by artistro08** [comment]
Not exactly sure how to extend the plugin. being honest. If you could share how to, that would be great. I'm not very proficient in PHP either

**Comment by tobias-kuendig** [comment]
I'll implement it in the stripe payment provider in the next few days. :+1:

**Comment by artistro08** [comment]
thank you

**Comment by tobias-kuendig** [comment]
I've added a feature that enables the customer to re-use their payment methods. The Stripe payment provider now creates proper Stripe customers and the payment methods get stored in mall as well.

If you want to test it see https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/158

Please only test this on a test system since it bumps the version up to 1.2.0 but we might release bugfixes on the 1.1 branch before this feature is released.

**Comment by artistro08** [comment]
awesome. Thank you. Will be testing soon

**Comment by artistro08** [comment]
having trouble trying to test this. how would I go about it? Do I use the edge updates setting in october?

**Comment by tobias-kuendig** [comment]
It's not released as an edge update yet. I'll be off next week and don't want to release anything anymore this week.

You'd have to manually clone this repo and checkout the `stripe-customers` branch. Then run `php artisan october:up`.
