### ISSUE TITLE
Handle the removal of variant properties correctly

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#17]
* [ ] Remove the data from the DB if a property's «Use for variants» option gets disabled

or 

* [ ] When calculating the available stock only check for properties that are «used for variants»

**Comment by amdad** [comment]
If second way will be chosen, hide those properties on backend relation lists and frontend component output.

**Comment by tobias-kuendig** [comment]
Thank you for your input! I'm currently working on this. I too opted for the removal approach. It makes thing unneccessary complicated if we keep the old properties.

**Comment by tobias-kuendig** [comment]
With e7cfb96594416c9d7e2805e8ace8aab5fa9adc7a and bfc5902a23b2798f7dcd9a5f283598c891a8ca07 property values are being removed from products if...

1. a property group is removed from a category
1. a property is removed from a property group
1. a property group is deleted
1. a property is deleted

Make sure to upgrade October to Build 443 to make this feature work.

**Comment by amdad** [comment]
AMAZING!!

**Comment by papppeter** [comment]
Hi,

i am facing a similar problem. 

i did unticked Use for variants, but it still shows that variant on product page, and i am not able to remove it even if i am editing the variant, it still shows there.

expected behavior would be if i am editing the variant, it saves only the Use for variants properties, and all other will be removed.
