### ISSUE TITLE
Usernames instead of Email

### ISSUE THREAD

**Issue by markusobi0** [OFFLINE-GmbH/oc-mall-plugin#183]
Not everyone want to login and register using a E-Mail, how about adding the possibility to use Usernames instead

**Comment by tobias-kuendig** [comment]
We are using RainLab.User which supports this. You can implement your own [`SignInHandler`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/SignInHandler.php) and [`SignUpHandler`](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/SignUpHandler.php) to use this feature.

We might add an out-of-the-box option in a future version but this has very low priority at the moment since it can be implemented with the provided interfaces.

**Comment by markusobi0** [comment]
Thanks for this tip.

**Comment by chrisvidal** [comment]
@markusobi0 Did you manage to implement your own signin / signup handler?

**Comment by tobias-kuendig** [comment]
Closing this as duplicate of #172
