### ISSUE TITLE
Ability to have addons that increase price. 

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#197]
So I'm not sure if this is an option, but I'm looking to create something like this this with the plugin 

![image](https://user-images.githubusercontent.com/6427230/56910168-82ce8f00-6a6f-11e9-8f35-ebdf1fc6933a.png)

a multiple selector for some fields. that increase the price of the product

![image](https://user-images.githubusercontent.com/6427230/56910202-9aa61300-6a6f-11e9-83f6-74c48130d9b9.png)

Is this currently possible with the fields there?

**Comment by tobias-kuendig** [comment]
Am I able to select multiple of these options at once or only one? If it's multiple at once you could do this via different Variants but you would need to do some manual wiring when these, let's say three selected variants, are added to the cart.

If a user can only select one you might be able to do this using the «Custom fields» dropdown option in the «Cart» section of the product form. You don't have to render the dropdown field but could override the partial and do the markup yourself. Just make sure the resulting request to the backend is the same.

Maybe if you describe the use-case in more detail I can tell you better if it is possible with the current state of the plugin.

**Comment by artistro08** [comment]
So what I would like to be able to do is select multiple items at once in a variant, on a product page. 

Lets say A guy wants ice cream on the site. He's on the product page "One Scoop Cone". There's a variant section that says "Toppings". In this section, They have a the option to add sprinkles, gummy bears, and fruity pebbles. He wants to pick two so he picks gummy bears and sprinkles. That's what I'm trying to create

here's another example too using the JKShop plugin: https://undeniablewigs.com/wigs/product/unic

**Comment by tobias-kuendig** [comment]
This should be done using custom fields, not variants.

Create dropdowns/checkbox options for each modification you want to provide. The checkbox options will have to be grouped somehow in the frontend since it's not yet possible to add "custom field groups" to a product.

We might add a "checkbox list" option in a future release that would help you solve this problem.

While it should be possible to implement this use-case it might need some hacking. 

Take a look at [the `onAddToCart` handler](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L217). This shows you how to [add a product ot the cart](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L235).

You can add any number of custom field values to this method. If the default component is not sufficient you might need to extend it and override the `onAddToCart` logic.

**Comment by artistro08** [comment]
Is it possible to add the checkmarks back?

**Comment by artistro08** [comment]
Meant to say "Checkbox list". Is it possible to add that feature in the near future?

**Comment by tobias-kuendig** [comment]
Sure, but I cannot give you a release date.

**Comment by artistro08** [comment]
No worries. Thank you

**Comment by artistro08** [comment]
Closing this because a similar feature solves my problem
