### ISSUE TITLE
Add datepicker for variants

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-mall-plugin#200]
For sale, such as a movie ticket, there is a need to add datepicker options to choose from. Can this be realized?

**Comment by tobias-kuendig** [comment]
Thank you for the feedback.

You can add a «Custom Field» in the «Cart» tab on the product form. This will allow the user to input any text since there is no date field yet. But you can attach a datepicker or change the markup of the field using component partials yourself (add some client side validation).

This is not a proper solution but might already be enough for your usecase. We will implement a out-of-the-box date field in a future release.

I'm closing this issue since https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/161 is similar.
