### ISSUE TITLE
Add to cart from categorie page

### ISSUE THREAD

**Issue by addoklopman** [OFFLINE-GmbH/oc-mall-plugin#237]
I need a way to add a product to a cart on a category page. This would be really awesome! Having a way to pass product options whit this as well would open so many possibilities.

**Comment by tobias-kuendig** [comment]
You can actually already do this. In your category component, add the following link inside the `item` loop:

```html
<div class="mall-products-item">
    <a class="mall-products-item__cart-button"
       href="javascript:;"
       data-request="{{ __SELF__ }}::onAddToCart"
       data-request-success="$.publish('mall.cart.productAdded')"
       data-request-data="product: '{{ item.hashId }}', variant: '{{ item.variantId }}'"
       data-request-flash
    >
        Add to cart
    </a>
	<!-- ... -->
</div>
```

Custom field values are not supported out-of-the-box here, though.

You can always extend the default Products component and add your own `onAddToCart` method. See here for all relevant code:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L225

I'm leaving the issue open since it makes sense to provide the same addToCart functionality in both components.

**Comment by addoklopman** [comment]
Perfect. I could for now use the veriants as a workaround. Product qty works as wel I see. Thank you so much for your reply!!

**Comment by addoklopman** [comment]
Sorry I tried adding this into the item loop but could not get it to work. Items would not show up in the cart. Do you have any more information on how I could implement this?

**Comment by tobias-kuendig** [comment]
Do you get an error? Is the `Products::onAddToCart` handler triggered? Are the needed values received? (`dd(input())`)

**Comment by tobias-kuendig** [comment]
The Products component now supports the same attributes in the `onAddToCart` handler, added in f650152.

See https://offline-gmbh.github.io/oc-mall-plugin/components/products.html#add-a-add-to-cart-button-on-the-category-page
