### ISSUE TITLE
Stock check does not take variants into account

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-mall-plugin#25]
I know that this is a WIP, but I will still log some issues I came accross here.

This one is in the Products component stock check: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L165-L176
This method simply takes the stock value from the base product, but does not take the availability of specific variants into account. 
A solution would be to check if the Inventory management method is set to "Variants" and then load the availabilities accordingly.

**Comment by tobias-kuendig** [comment]
According to [the scripts.htm partial](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/product/scripts.htm#L29 ) this method is only called if no properties are available - so it's technically a base product without variants.

If properties are available the [onChangeProperty event handler](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L152) is called via [JS event](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/product/scripts.htm#L15) which takes different variants into account.

I guess we should refactor this and display the available stock directly if the management method is set to `single`. Otherwise reuse the stock calculation from the `onChangeProperty` linked above.

**Comment by alxy** [comment]
I'm not sure if I get it correctly, however if I set up variants and group by a single property (which is package size in my case), then the default component markup renders simple links with images to change the variant: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/product/cart.htm#L6-L11

Then there are no other properties left which would render the select inputs which actually trigger the ``onChangeProperty`` event. I guess this only works for the case that "Attribute for variant grouping" is "None". In this case the select input correctly renders and triggers the event. But in the former case ``firstProperty.length`` will yield 0 and incorreclty ``onCheckProductStock`` will be run. This now fails to calculate the stock with ``{"X_OCTOBER_ERROR_FIELDS":[["Missing input data"]],"X_OCTOBER_ERROR_MESSAGE":"Missing input data"}``.

**Comment by tobias-kuendig** [comment]
This should be fixed in 128daca

**Comment by tobias-kuendig** [comment]
This is looking good in the latest version. I'll close this for now.
