### ISSUE TITLE
Set currency for frontend

### ISSUE THREAD

**Issue by HomaEEE** [OFFLINE-GmbH/oc-mall-plugin#284]
Hello, can I set different currency for frontend by default?
for example in backend I set USD for price, but I want EUR in frontend for users

**Comment by tobias-kuendig** [comment]
You can [force the active currency](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/Currency.php#L134) by calling 
```
Currency::setActiveCurrency(Currency::where('code', 'EUR')->first())
```
or set the "is default" switch to active in the backend settings of the plugin. This will set the active currency for new sessions automatically. It's important that you clear your session or use an incognito window to check these settings since it's only used when a new user session is created.

**Comment by HomaEEE** [comment]
this code for index page? I try it - but I have error:
Parse error: syntax error, unexpected 'Currency' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

**Comment by tobias-kuendig** [comment]
You have to do use it in a custom component or in your layouts's lifecycle method.

```
name = "default"
==
use OFFLINE\Mall\Models\Currency;

function onStart()
{
    Currency::setActiveCurrency(Currency::resolve('EUR'));
}
==

Page content
```

see https://octobercms.com/docs/cms/layouts#layout-life-cycle
