### ISSUE TITLE
Property per product

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#289]
Hi @tobias-kuendig 

if I understand correctly the models, currently the properties are attached to category.

I kind of need to have property per product, how could I handle these if it is possible?

**Comment by chrisvidal** [comment]
why I am asking, is because I am facing a `Allocated memory error' when i want to open a product, in the backend or in the frontend.

My property group set up is like this:
I have one property group handling 500 different properties, for all my 1600 products.
I guess this is the bottleneck.

in the component product following code line 505:

```php
return $this->product->categories->flatMap->properties->map(function (Property $property) use ($valueMap) {
            $values = $valueMap->get($property->id);

            return (object)[
                'property' => $property,
                'values'   => optional($values)->unique('value'),
            ];
        })->filter(function ($collection) {
            if ($this->variant && $collection->property->pivot->use_for_variants != true) {
                return false;
            }

            return $collection->values && $collection->values->count() > 0;
        })->keyBy(function ($value) {
            return $value->property->id;
        });
```

**Comment by tobias-kuendig** [comment]
> I kind of need to have property per product, how could I handle these if it is possible?

This is not possible with Mall. Properties need to be attached to a Category so generating category filters are feasible. Having x Products in a Category that have x different Properties with x different possible values would make the querying even more compliated that it already is.

>  I have one property group handling 1800 different properties, for all my 1600 products.

This is an enormous number of properties. Since this is such an edge case I won't spend the time and improve the bottleneck you posted. If you find a more efficient way to resolve the property values (which I'm sure there is!) please submit a PR. The code above should be possible to refactor to a few DB queries that do most of the heavy lifting.

**Comment by chrisvidal** [comment]
thanks @tobias-kuendig 

after digging into my config, I have one property group where I put my 1600 properties.
The property group is attached to all the first level categories.

my problem came from the fact that she categories had few times this property group attached, so there were some exponential increase in the calculation to be done bu this piece of code.
I cleared it and it works fine
