### ISSUE TITLE
How to add existing user as a shop customer

### ISSUE THREAD

**Issue by envas** [OFFLINE-GmbH/oc-mall-plugin#325]
I have a web site with a lot of existing users. I am going to add a shop to the site where only a subset of existing users should be able to use and purchase products over the internet. Is it ever possible to attach a shop model to an existing October user?

Currently, I found the only way to create another account (e.g. new registration), which violates the single-sign-on idea, and, that's worse, has terrible side effects. For example, after new registration with the existing user's email, I got duplicate emails in the table `users` even when the email is defined as the login username and should be in my opinion unique. Not sure if it is the Mall or October issue.

**Comment by tobias-kuendig** [comment]
You could implement your own SignUpHandler:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/DefaultSignUpHandler.php

... and register your own implementation in the service container:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/registration/BootServiceContainer.php#L32

If you want an easier way just create `Customer` models for all users. The relationship between the User and Customer models is a simple `hasOne`:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/User.php#L10

The email column is no longer unique on purpose in Mall since mulitple guest accounts with the same email address may exist. We have made changes to this feature in some of the latest versions though, so we could think about adding the unique constraint back in.

**Comment by envas** [comment]
Thank you for your quick answer. I will have a look at it.

**Comment by tobias-kuendig** [comment]
Great, feel free to reply if you need any further assistance.

**Comment by TimFoerster** [comment]
If any other person has the same problem:

simply validate, if there is a customer, i entered that in my layout:
```

[quickCheckout]
step = "{{ :step }}"
loginPage = 'auth/login'
==
function onInit() {

    $user = \Auth::user();
    // No customer found, create it
    if ($user && !$user->customer) {

        $customer            = new \OFFLINE\Mall\Models\Customer();
        $customer->firstname = $user->name;
        $customer->lastname  = $user->surname;
        $customer->user_id   = $user->id;
        $customer->is_guest  = false;
        $customer->save();

        if ($user->street_addr) {

            $address = new \OFFLINE\Mall\Models\Address();
            $address->fill([
                'company' => $user->company,
                'lines' => $user->street_addr,
                'zip' => $user->zip,
                'city' => $user->city,
                'state_id' => $user->state_id,
                'country_id' => $user->country_id
            ]);
            $address->customer_id = $customer->id;
            $address->save();
            $customer->default_billing_address_id = $address->id;
            $customer->default_shipping_address_id = $address->id;
        }

        $user->customer = $customer;
        return Redirect::refresh();
    }
}
```
