### ISSUE TITLE
Change order number to INT in default migration

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#365]
if i try to sort with order ids it give me wrong order.

![Screenshot_91](https://user-images.githubusercontent.com/3380880/68101725-63596880-fecf-11e9-8f49-e6bb6e10baf5.png)

**Comment by tobias-kuendig** [comment]
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/updates/create_offline_mall_orders.php#L14

This is because the order number is created as a VARCHAR column to accomodate for order numbers that include letters.

If you've only got integers as order number you can safely change the column's type to INT and the sorting should work as expected. 

We might change this to the defafult behaviour in a future version.

**Comment by papppeter** [comment]
thanks, it fixed for me.

**Comment by tobias-kuendig** [comment]
The default has been changed in b8c490c, thanks @papppeter for the report!
