### ISSUE TITLE
Categorys with products counter

### ISSUE THREAD

**Issue by haralake** [OFFLINE-GmbH/oc-mall-plugin#376]
I'm using successfully static menu component to display eshop categories on a partial, but i try to find a way to also display products count number on every category. Is this possible?

````
            {% if staticMenu.menuItems %}
            {% set items = staticMenu.menuItems %}
            {% for item in items %}
            <a href="{{ item.url }}" class="">
                <span>{{ item.title }}</span>
                <span>"""""{{ products.items.count }}"""""</span>
            </a>
            .............
````

**Comment by tobias-kuendig** [comment]
The staticMenu component holds a collection of the Pages plugin's MenuItem classes. I'm not aware of any possibility to store meta information with a MenuItem where we could pass the Mall Category and it's releastions along:
https://github.com/rainlab/pages-plugin/blob/master/classes/MenuItem.php

If you want to display the product count you would have to 

1. build your own implementation of the menu
2. Build a map of the category and product counts inside your partial and reference it in your for loop. You would have to use the title or URL as key, since we don't have access to the original ID. Also, be aware that the title might not be unique enough, depending on your setup.

```php
// Untested!
==
function onStart()
{
    $this['counts'] = \OFFLINE\Mall\Models\Category::with('products')->get()->mapWithKeys(function($category) {
        return [$category->title => $category->products->count()];
    });
}
==
{% for item in items %}
<a href="{{ item.url }}" class="">
    <span>{{ item.title }}</span>
    <span>{{ counts[item.title] }}</span>
</a>
{% endfor %}
```

I'd opt for option 2, but be aware that this code is rather inefficient if you have lots of categories/products.

**Comment by tobias-kuendig** [comment]
Feel free to reply if you need any further support.

**Comment by haralake** [comment]
In Rainlab blog plugin and specific in category model they use:
```
/**
     * Count posts in this and nested categories
     * @return int
     */
    public function getNestedPostCount()
    {
        return $this->post_count + $this->children->sum(function ($category) {
            return $category->getNestedPostCount();
        });
    }
```
this way you can display post counts on categories using:
```
{% if blogCategories.categories %}
    {% for category in categories %}
    {% set postCount = category.post_count %}
        <span>{{ category.name }}</span>
        <span>{{ postCount }}</span>
    {% endif %}
{% endfor %}
```
I was wondering if we could use the same logic to represent the number of products by category.
