### ISSUE TITLE
Cart component

### ISSUE THREAD

**Issue by MateThemes** [OFFLINE-GmbH/oc-mall-plugin#391]
Hello!

I try to change the markup for the cart component. I copied it from the plugin (component/cart) in the theme folder. And changed it to partial 'cart/default.htm'

But now if I apply any markup changes nothing will be changed. Does anyone have experience with this?

Thanks in advance!

**Comment by tobias-kuendig** [comment]
This is not a problem that concerns this plugin since the override functionality is provided by October itself. Does your `cart` component have an alias? Did you check the case of your partials? Overrides may be case-sensitive depending on your OS.

Also make sure to read the corresponding docs: https://octobercms.com/docs/cms/components#overriding-partials

**Comment by MateThemes** [comment]
This is a strange behaviour, coz I am overriding a lot of components via partials the same way.

I will double check my spelling. And give you then feedback!

Thank you very much!

**Comment by MateThemes** [comment]
I double checked the partials and the name and the spelling. I also read the partials override documentation. But It don't work for me. 

Maybe it is because, the partial is cart and the table where the entries of the cart are is in a subfolder. I don't know. 

Any ideas?

**Comment by tobias-kuendig** [comment]
You did not mention the subfolders! :grin: 

You have to patch your installation manually or override the complete folder structure until this is merged:

https://github.com/octobercms/october/pull/4652

**Comment by tobias-kuendig** [comment]
A fix for this problem has been merged into October and will be available in a future release:
https://github.com/octobercms/october/pull/4652
