### ISSUE TITLE
Checkout remove items

### ISSUE THREAD

**Issue by MateThemes** [OFFLINE-GmbH/oc-mall-plugin#395]
Hello!

I have a question to the cart component. 

I have items in the cart and remove them. The begin checkout button is still visible and I can begin a checkout. If I force a page reload manually the button disappear.

How can I force a complete page reload that the button is not visible if I remove items and the cart is empty after that?

Thanks in advance!

**Comment by tobias-kuendig** [comment]
Thank you for this input!

:thinking:  I guess the easiest solution for this is if we add a `include proceed to checkout button` property that conditionally includes the button in the component itself. Otherwise it won't be possible to remove the button outside the component once no more products are available.

As it would be `false` by default, this would not break existing installations.

**Comment by tobias-kuendig** [comment]
This was added in fee07ab, thanks @MateThemes!
