### ISSUE TITLE
Simple methods to manage addresses (update, delete, create....)

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#397]
Hello,

I develop a website with an heavy theming of all oc-mall components. Quite happy for now, everything is quite easy to understand and customize (maybe just too much partials IMHO 😄)

However, I found that addresses system is a bit behind. The addressForm component require you setup a page dedicated to address management as it need some URL parameters in order to work (address token, redirect url etc....). I'm planning to have only one account page where everything is loaded and edited using ajax api, I'm obliged to write my own save methods for addresses as I can't use the addressForm component that way. It's a shame. In addition, if you want to list countries, you have to attach the signUp component cause country list is attached to it (sounds more logical to attach country list to addressForm component instead).

All of this is minor issues as I just need to write my own methods to fix it, but it's a shame to not have a more flexible address component could do the job without any extra logic.

Best regards, and congratulation for your excellent ecommerce system.

**Comment by tobias-kuendig** [comment]
```
[addressForm]
address = 1
set = "both"
==

{% component 'addressForm' %}
```

Does this not work for you?

The usage of URL parameters is completely optional since the parameters are directly passed to the address form component as properties.
 
https://offline-gmbh.github.io/oc-mall-plugin/components/address-form.html

>  In addition, if you want to list countries, you have to attach the signUp component cause country list is attached to it

Did you see that there is [a countries property](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/AddressForm.php#L27) that [includes all countries as a Collection](https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/AddressForm.php#L134)?

**Comment by Zmove** [comment]
Hello,

Your suggestion works, I finally made my custom method cause I saw your answer too late (my fault, not yours, you were very reactive), but it works.

Best regards,

Alex
