### ISSUE TITLE
Normalize casing of component properties

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-mall-plugin#40]
Some are `snake_case` others are `camelCase`

**Comment by amdad** [comment]
I also think, we should rename Category component to Products component. Add new params/options/filters to it, so it will be usable also to display promoted products, random, latest etc.

**Comment by amdad** [comment]
I will do this tonight. camelCase style like octoFather did: https://github.com/rainlab/blog-plugin/blob/master/components/Posts.php

I also think, we should rename Category component to Products component. Add filters to it, so it will be usable also to display promoted products, random, latest etc.

Filtering by category slug, or specific category, or none, so it will display all products with limit number instead of pagination. Every option should be optional to get any product list with pagination or not. What do you think?

**Comment by amdad** [comment]
I will do this tonight. camelCase style like octoFather did: https://github.com/rainlab/blog-plugin/blob/master/components/Posts.php
