### ISSUE TITLE
Postfinance payements

### ISSUE THREAD

**Issue by adoudiet** [OFFLINE-GmbH/oc-mall-plugin#418]
Please add if possible postfinance and datatrans for Switerzland.
Bests regards Alain Doudiet

**Comment by tobias-kuendig** [comment]
There is a WIP implementation on the datatrans branch, you're welcome to add improvements to this:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/tree/datatrans

We don't develop this actively because we don't have a project using Datatrans at the moment. We might implement it once a project comes along.

**Comment by Zmove** [comment]
Hi, I have the same need for Postfinance. @tobias-kuendig would you accept a bounty for this ?

@adoudiet would you be ok to pay a bounty with me to help tobias developping it if bounty are accepted ?

**Comment by tobias-kuendig** [comment]
This should get you going:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/422

Let me know if any more settings or other changes are required. 

I'm counting on you @adoudiet and @Zmove to test and finalize this PR! ;-)

**Comment by Zmove** [comment]
@tobias-kuendig you are the best :), let's finalize this !
