### ISSUE TITLE
Error when redirected to checkout/done page after payment

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#421]
Hello,

When I complete payment to the bank page and I'm redirected to the checkout done page, I get a fatal error : 

`Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getCurrent() on null in /vendor/twig/twig/src/Parser.php:332`

Do you have an idea about what could be the cause of the error ?

Here is my complete function actually : 

     public function complete(PaymentResult $result): PaymentResult
    {
        //$data = Request::all();
        //return $result->success($data, 'Status : '.$data['STATUS']);
        return $result->success([], '');
    }

Best regards,

Alex

**Comment by tobias-kuendig** [comment]
I guess this is a duplicate of https://github.com/OFFLINE-GmbH/oc-mall-plugin/issues/258

Currently, October does not support calling a custom Twig function from inside the mail partials. This is what happens if you format a price using the ` | money` filter, which calls Twig::parse under the hood.

This is an extremely time consuming and complicated problem to debug.

**Comment by Zmove** [comment]
Seems to be the case cause if I disable email notification, it works. I close that issue in the benefits of #258 which is fare more complete.

**Comment by zlobec** [comment]
@Zmove Which notification should be disabled?

**Comment by Zmove** [comment]
I disabled them all. Waiting for an official solution
