### ISSUE TITLE
Taxes don't take applied discounts into account

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#423]
i think on discount there is an issue with the the tax calculation. please check the picture

![Screenshot_164](https://user-images.githubusercontent.com/3380880/72260487-451c9100-3613-11ea-93c7-5966a320c14d.png)

**Comment by tobias-kuendig** [comment]
638 would be 27% tax on the 3000. It looks like the tax calculation does not take the reduced price into account. I'll have a look at this, thank you!

**Comment by papppeter** [comment]
yes tax looks itself ok. only discount is a problem.
thanks!

**Comment by shiftaltd** [comment]
Hi. Is a fix for this planned ?

**Comment by dathwa** [comment]
This issue is still present for me. Any update on this? Thanks.

**Comment by CarolinePublipresse** [comment]
Hi, 
Same problem here. 
The taxes total is calculated from the total without Discounts. This is wrong and is a legal mater. In France, the tax amount must be shown on invoices, and must be calculated regarding of what the client will really pay. 

See the example below : 
![image](https://user-images.githubusercontent.com/84564072/155746114-a8dede79-c389-41b3-8cb8-76cb258ef046.png)

Here are my calculs : 
`{% set taxRate = quickCheckout.cart.totals.taxes.first.tax.percentage / 100 + 1 %}` **
Total before discounts : `{{ (quickCheckout.cart.totals.totalPreTaxes)|money }}`
Total after discounts    : `{{ (quickCheckout.cart.totals.totalPreTaxes - (quickCheckout.cart.totals.totalDiscounts / taxRate) )|money }}`

** I cheated a bit on this, because I'm lucky : in my client case, there is only one tax value. If the shipping or different products were having different tax rates, it would be much more complicated to calculate :/

So my point is : the tax total must be calculated on the total PreTax, but after Discount is applied. 

Does anyone planned to work on this ? It's a huge work, and may need the developer to work in collaboration with a chartered accountant. And I don't know how it works for other countries...

In the meantime, whe have to tweak the tax total amount on every place it is shown...

Thanks for your thoughts on the subject ;)

**Comment by tobias-kuendig** [comment]
No update so far and I do not have the ressources at the moment to dive into this.

Anyone who is affected by this problem and has some spare time, feel free to submit a PR with a fix.

**Comment by SamBrishes** [comment]
Hello,

as far as I could test, this problem should be fully solved with the upcoming 3.2.0 release and the new PriceBag handling. (#1082)

~ Sam.
