### ISSUE TITLE
Category & Products hashids errors with the seed database 

### ISSUE THREAD

**Issue by DrakusorU** [OFFLINE-GmbH/oc-mall-plugin#443]
tried to use the seed database or whatever it is called, so I have some content on the page and I get these errors, reseting the plugin and the database and creating new products and categories works fine.. im on version 1.11.0

this is the system log https://pastebin.com/yjed7Mq8 and a screenshot https://prnt.sc/qx33dm

EDIT: actually with a fresh install, it does it only when you want to visit a product page, it works fine with the categories unlike the previous case. 

EDIT 2: **composer require hashids/hashids** solved the problem but I don't know why it was missing or whatever happened.

**Comment by tobias-kuendig** [comment]
Thank you for this report. How did you install the plugin? (Composer, git, marketplace)

**Comment by DrakusorU** [comment]
I downloaded the files from here so I can get the last version because on the market was still waiting approval then I did the plugin:refresh thing

**Comment by tobias-kuendig** [comment]
When you download a plugin manually, you have to make sure to run `composer install` from your installations's root directory, otherwise you will be missing the vendor dependencies.

If you download the plugin via the marketplace, these dependencies are bundled so you don't have to do anything manually.
