### ISSUE TITLE
Variation url

### ISSUE THREAD

**Issue by skacco** [OFFLINE-GmbH/oc-mall-plugin#552]
Hello I want to understand if is it possible to fix product url when products has variant.
I explain.
I have a shoes with three color: red, black and white.
I set to don't show variant in the catalogue list, so I will see only the first product "red shoes".
But the url of the product contain some characters on the end like this : https://mall.offline.swiss/en/product/cruiser-1000/g3dxMq6L
For SEO purpose I want to remove the final part.
Is it possible to fix this problem?

**Comment by tobias-kuendig** [comment]
The redirect happens here: https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/Product.php#L202

A variant ID is required for the component to work correclty (after all, you are viewing a variant ("red shoes"), even if you linked to "shoes" directly). We could try and set the variant ID in the component internally instead of running the redirect.

**Comment by skacco** [comment]
Yes it will be very good for SEO... I wait for your update thank you very much

**Comment by tobias-kuendig** [comment]
The redirect has been removed in 0c3573d. The first Variant will now be used internally instead of redirecting the page. This change is available in version 1.11.26
