### ISSUE TITLE
There must be phone number on signup page in checkout steps

### ISSUE THREAD

**Issue by amjadniazi48** [OFFLINE-GmbH/oc-mall-plugin#557]
There must be phone number on signup page in checkout steps, its most important and necessary, I have tried to make it possible on registration page by extending the user plugin but it is  not saving from frontend, please anybody know how to do this

        public function boot(){
       
  
             UserModel::extend(function ($model){
                 $model->addFillable([
                     'phone',
                 ]);
         });

**Comment by chrisvidal** [comment]
you need to override the twig partial `signup` and add yourself the `phone` field on the frontend.
then you need to check the `SignUpHandler.php` to see whether it takes in all the input form fields or not.
If not, you will have to override this class yourself to take in account your new field.

**Comment by tobias-kuendig** [comment]
Also see #172, we will make this easier in the future.

**Comment by PubliAlex** [comment]
+1 for phone field by default, that should be attached to address model and not customer profile (or maybe both ?). Many carrier require a phone number in case of delivery problem, and, as you can manage addressbook and have a different shipping and billing address, it make sense to ask for the phone number when you ask for the address, because the phone number of the person that receive the package can be different than the phone number of the person that receive the invoice.

**Comment by Zmove** [comment]
+1 for phone too, it's a must have for ecommerce today and most delivery company require one now (at least in France)
