### ISSUE TITLE
Question about guest emails and date suffixes

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#613]
Hi @tobias-kuendig ,

I've been working hard on my first implementation of the Mall Plugin and I am loving it. Most things are so clear and elegant, thanks for your hard work.

I do have a question though about how guest email accounts are treated by the Mall Plugin. In my order overview, I'm seeing constructions with a date suffix like below:

`firstname.lastname@gmail.com_old_2020-10-20_201253`

I've searched the documentation, but cannot find any references to those suffixes. I'm guessing it has something to do with GDPR and to have the ability to be able to delete or randomize those email addresses after a certain period of time?

I did encounter an issue which I haven't been able to reproduce where I was logged in as a guest, and placed a second or third order (my original session was still active). The order notifications didn't arrive, because (I'm guessing) my email address had already been rewritten to a construction with a date suffix. 

Could you kindly elaborate how these suffixes are used and what the exact mechanism behind it is?
Also, could you look into the issue I've described?

Thanks in advance.

**Comment by tobias-kuendig** [comment]
Let's say you sign up as a guest using `first.last@gmail.com`. This address is now active for as long as you browse the store. 

If for a subsequent purchase you sign up as a guest again, using the same email, we need to make sure the email is still only registered once. That's why the email address of the old guest account gets changed so we can register a new guest account. This happens here:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/customer/DefaultSignUpHandler.php#L90

This is done to stay in line with the RainLab.User plugin which only allows an email address to be used once (it even has a unique constraint on the table).

In your case, the old guest account should not have been renamed before you sign up as a guest with the same email address again.

**Comment by maartenmachiels** [comment]
Thank you @tobias-kuendig - this is very clear. I'll reopen this in case I encounter any irregularities, but I'm guessing it works as it should.
