### ISSUE TITLE
[Quickcheckout] Filter ShippingMethods depending on customer country

### ISSUE THREAD

**Issue by TimFoerster** [OFFLINE-GmbH/oc-mall-plugin#658]
![image](https://user-images.githubusercontent.com/7849550/100896270-bcbf0d00-34be-11eb-953c-851684f9b3b7.png)

Shipping methods are not filtered, even if country is selected.

**Comment by Zmove** [comment]
I just wanted to post an issue about this, and I saw your post, so +1.

With the new quickCheckout component, the shipping method listing completely ignore country restriction.

**Comment by tobias-kuendig** [comment]
Looks like the culprit is this line:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/components/QuickCheckout.php#L409

We cannot get the methods by cart since the cart is only updated when the user hits "checkout". We need to either:

1. update the cart if the user changes the country dropdown (preffered)
1. add a `getByCountry` method to the `ShippingMethod` model and call it when the dropdown changes

**Comment by PubliAlex** [comment]
@TimFoerster did you find a solution to this, I have the same problem. And we have to refresh shipping methods not only when user select a country in the dropdown, but also when the user choose an address in it's addressbook dropdown

**Comment by PubliAlex** [comment]
One possible solution I just found is to trigger quickCheckout::onRun and update your shipping method partial after that. I tested and it works when you change address using the address selector.

Something like that : 

<script>
    function updateShippingMethods() {
        $.request('quickCheckout::onRun', {
            update: { 
                'partial/containing/shippingmethods': $('#wrapper-div'),
            },
        })
    }
</script>

that you trigger on data-request-success of your element that trigger AddressSelector::onUpdateAddress

But it doesn't work when you change country in billing or shipping address when you checkout as anonymous, it's because the ShippingMethod->getAvailableByCart() function doesn't take that field into consideration. The request that return shipping method list should first try to get the country_id of the selected shipping country, before trying to get it on $cart->shipping_address->country_id and it should do the job.

Best regards,

Alex

**Comment by PubliAlex** [comment]
Just created a [PR ](https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/828) to fix the problem.

I modified the ShippingMethod->getAvailableByCart() function to take post('country_id') when present, instead of $cart->shipping_address->country_id

It allow themers to display the right shiping methods for the right country, even if the user is still anonymous and don't have $cart->shipping_address registered yet.

Here is my code below : 

```
            {{ form_select_country(id, countryId, {
                class: 'form-select',
                required: true,
                id: id,
                emptyOption: ('Choisissez'|_ ),
                    'data-request': 'onInit',
                    'data-request-data' : ("type: '" ~ type ~ "'"),
                    'data-request-update': {
                        'mall/checkout/overview/guest/countrystate' : ('#countrystate-' ~ type ~ '-wrapper')
                    },
                    'data-request-success': 'updateShippingMethods()',
            }) }}
```

And my function updateShippingMethods()

```
<script>
    function updateShippingMethods() {
        var countryId = $('#shipping_country_id').val();
        if(countryId == '') {
            countryId = $('#billing_country_id').val();
        }
        
        $.request('quickCheckout::onRun', {
            data: { country_id: countryId },
            update: { 
                'mall/checkout/overview/shippingmethods': $('#shipping-method-wrapper'),
            },
        })
    }
</script>
```

**Comment by tobias-kuendig** [comment]
This issue has been fixed. Thank you all for your reports!

Please see 545fb61 for details
