### ISSUE TITLE
How to schedule aftersales e-mail

### ISSUE THREAD

**Issue by nolyboms** [OFFLINE-GmbH/oc-mall-plugin#704]
I would like to set up a cron job for sending an email to customers who successfully bought a product 4 weeks after they successfully paid.

In my custom plugin i have this first approach:

```
use OFFLINE\Mall\Models\Order as Order;
.
.

public function registerSchedule($schedule)
{
        $schedule->call(function () {

			// here we need to check the date of payment in the db:  offlin_mall_orders -> paid_at
			//
			// and get the related user
			//
                        // then we send the mail to each user

            foreach ($users as $user) {

                Mail::send('my.aftersales::mail.customer', $data, function($message) use ($user) {
                    $message->to($user->email, $user->name);
                });

            }
            
        })->everyMinute();

}
```

I really appreciate it if someone in the community could please help with the code.

**Comment by tobias-kuendig** [comment]
The scheduler approach is the way to go. Are you struggling with writing the query? It should be something like this (untested):

```php
$orders = Order::with('customer.user')->whereDate('paid_at', today()->subWeeks(4))->get();

foreach ($orders as $order) {
    $user = $order->customer->user;
    info('sending mail', ['user' => $user->email]);
}
```

Maybe only run the job once per day and select the orders with `whereDate`. This ignores the time completely. Otherwise, make sure to at least ignore the seconds from the timestamp to prevent missing orders or triggering the mails twice.

The nicest solution would be to add a `aftersales_mail_sent_at` column to the order table to store the date you have sent the e-mail. Then you can query only by orders that don't have this date set. This way you will never miss an order and never send the e-mail twice.
