### ISSUE TITLE
[bug] Shipping cost not refreshed when deleting product on the cart

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-mall-plugin#713]
Here is how to reproduce : 
- create 2 different shipping : one of 10€ for an order < 100€ | one of 0€ for an order >= 100€
- Add some product to your cart to have an order > 100€. The shipping 0 apply, it's OK
- Play with the product quantity field to try to be under or above 100€. It works
- Now get an order of > 100€ to have 0€ shipping applied, and delete a product in the cart that transform the order price < 100€
- The shipping is not refreshed, the 0€ shipping is still displayed whereas your order is < 100€

Refreshing the page correct the problem, but it lead to confusion for the user.

**Comment by stnKrisna** [comment]
@tobias-kuendig Gonna try fix this bug today

**Comment by xyzqtc** [comment]
How did you fix this problem?

**Comment by stnKrisna** [comment]
@xyzqtc See here https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/baa5330af836f56aa5132e3bf06ee4ded0fe4e1b

**Comment by xyzqtc** [comment]
@stnKrisna thanks for the quick reply! Well the problem is that in a situation like this:
I have a quick mini cart that is showing the shipping costs too (shipping method)

1. Shipping Method Standard
2. Shipping Method Free if total > 100 $.

User starts adding products one by one.
Step 1:
 - add Product 1 - price 25 $:
 - cart total 25 $
 - shipping method is set as standard because only standard is available in that situation
Step 2:
 - add Product 1 - price 25 $:
 - cart total 50 $
 - shipping method isnt updated, its only validated
 
 Step 2:
 - add Product 3 - price 100 $:
 - cart total 150 $
 - shipping method isnt updated, its only validated and it stays as standard shipping method although free shipping is now available.
