### ISSUE TITLE
Currencies support issues

### ISSUE THREAD

**Issue by amdad** [OFFLINE-GmbH/oc-mall-plugin#72]
Hard to debug, and how to recreate this, But shop is able to forget to display all prices. All prices can get 0.00 values instead correct prices. Problem is able to fix them-self after a longer while.  But if it come back it's critical error. Any idea what could have happened, to cause problem like this in newest version?

I will test it further to get any more useful information about this.

**Comment by amdad** [comment]
OK, I'll think I found a trace. It's problem with currencies. When switch to different currency it cause this. Currency rates seems to fail on save on backend. Need to test it out further to be sure how to recreate this.

**Comment by tobias-kuendig** [comment]
The problem will be this line:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/af1a3784b6f70a218a953dad7fd656380aee6770/controllers/Products.php#L45

It disables inheritance for the next page load. If you don't save the form and reload the frontend instead the variants won't inherit the product's properties.

This is only an issue for admins and solved by just reloading the page. 

Maybe we can make this work better by adding a `app()->runningInBackend()` check since the inheritance will only ever be disabled in the backend where the base properties of variants are edited.

**Comment by amdad** [comment]
I doesn't understand your reply, what exactly admin should do/shouldn't do to prevent problem?

**Comment by tobias-kuendig** [comment]
Most of these issues should be fixed in the `currency-problems` branch. The price filter on the category page does not yet work for automatically calculated prices in other currencies. 

* Conversion rates now have a precision of up to 4 decimals
* Prices in other currencies that are not set explicitly are calculated using the conversion rate
* A new `php artisan mall:check` command was added to check for consistency errors of the installation. More checks will be added.
* Pricing information for currencies gets deleted when the currency itself is deleted
* Currencies added after a product was created don't break the system anymore

**Comment by amdad** [comment]
Thanks, I will test it today afternoon.

**Comment by tobias-kuendig** [comment]
It's available in develop now.

**Comment by tobias-kuendig** [comment]
Fixed due to inactivity. Feel free to comment again if the problem persists.

**Comment by ajsaces** [comment]
I am deploying a different version of a working dev on a different server and I seem to be facing this default currency issue now? I am using a new default currency AUD. All my pricing though is trying to use euro as default for some reason. I have reset/readded/removed/refreshed cache/reindexed but cant flush. I have added new products and same thing the new products still try to use euro as default? What am I missing. I have also tried using both filesystem and database options as "index driver" (havent quiet worked out which one is best for my env but thats another story.

**Comment by tobias-kuendig** [comment]
Are you seeing the wrong currency in the frontend or the backend?

**Comment by ajsaces** [comment]
Frontend

Backend: Inside the individual product edit see price + AUD. On the backend/offline/mall/products overall summary page prices are empty

**Comment by tobias-kuendig** [comment]
Sorry, it's hard to help you without more detailed information.

1. Did you have products created and then you switched the default currency?
1. Did you try to logout/login again in the frontend or open the website in a incognito tab? The default display currency is stored in the user's session so as long as you don't sign back in or change the currency manually it will not be switched.
1. What does `price + AUD` mean? Can you post a screenshot of what is wrong?
1. Is the currently stored pricing information when editing a product correct?

**Comment by ajsaces** [comment]
Backend default currency AUD set
![image](https://user-images.githubusercontent.com/46471237/55706904-b2b4e480-5a25-11e9-864c-6ddc5f399900.png)

![image](https://user-images.githubusercontent.com/46471237/55706944-c8c2a500-5a25-11e9-8142-a865886b9148.png)

Products pricing set to AUD

Frontend shows euro?:
![image](https://user-images.githubusercontent.com/46471237/55707338-b5fca000-5a26-11e9-85ee-4f6f13dd4ff2.png)

![image](https://user-images.githubusercontent.com/46471237/55707233-7635b880-5a26-11e9-9593-b063f9c44d05.png)

**Comment by ajsaces** [comment]
1. initially they may have been set to default - but I added products after as well
2. yes logged out, cleared cache. rebooted
3. attached - AUD = Australian Dollar sorry. This all works on localhost.
4. pricing appears correctly input however, on the backend products overview page the prices dont show as expected and on my localhost version

![image](https://user-images.githubusercontent.com/46471237/55707703-91ed8e80-5a27-11e9-8196-48099717b851.png)

**Comment by tobias-kuendig** [comment]
Thank you for your response. 

Could you check if you've got a `Format` set for the active currency (in the Twig editor) on the server where the price column is displayed empty? 

Also, just to make sure, there is nothing logged in your `system.log` and `php artisan mall:check` returns no errors, right?

**Comment by tobias-kuendig** [comment]
Another thought: Would it be possible that you did not enter any price in AUD yet?

**Comment by ajsaces** [comment]
no errors, nothing in log about currencies. I just went back to the start and reinstalled from scratch and it now works. So it must have been something when setting up the default currency and products. Anyway sorry couldn't identify anything further. Hopefully it was just my issue.

**Comment by ajsaces** [comment]
thanks for your help
