### ISSUE TITLE
Dynamic pricing for single product

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#720]
Hi. Just wondering if this is possible, and what the best approach might be.
Client sells virtual products, e.g. lessons, in multiple combinations.
I will have just one product in the backend catalog - "Lessons", initial price of £1.00.
After customer chooses lessons from my custom forms, I calculate the price dynamically, and I want to add the "Lessons" product to the cart, and assign the caluculated price - e.g. £345.66.
Any tips, pointers very much appreciated.
Thank-you.

**Comment by tobias-kuendig** [comment]
There is a `mall.cart.product.added` event you might use to update the price of the product that is in the cart:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/models/CartProduct.php#L61

Otherwise, if you already have custom code going, you could implement a custom `addToCart` method that sets the price on the model. After all, adding a product to the cart is nothing more than creating a `CartProduct` pivot model:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/5998e993db31c9bcd44c52b645dd9fa35ee797c5/classes/traits/cart/CartActions.php#L26

**Comment by dathwa** [comment]
Perfect. Thank-you.
