### ISSUE TITLE
MallPDF

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-mall-plugin#757]
OC 1.0.472  
Mall plugin : 1.13.2  

I get an error while exporting wishlist to PDF : 
```
An exception has been thrown during the rendering of a template ("The component 'cart' is not found.").
P:/_Sites/project/themes/mytheme/partials/mallPDF/wishlist/table.htm line 3
```
The wishlist page work's fine.

**Comment by tobias-kuendig** [comment]
I cannot reproduce this using the demo theme.

This error probably occurs because the default PDF partials from the demo theme refer the order component:
https://github.com/OFFLINE-GmbH/oc-mall-theme/blob/master/partials/mallPDF/wishlist/table.htm#L11

Make sure to put this on your layout, so it is available for the wishlist partials.

Let me know if this does not fix the problem.
