### ISSUE TITLE
Can't create a new product (clean installation October CMS v2.1.4)

### ISSUE THREAD

**Issue by SebastiaanKloos** [OFFLINE-GmbH/oc-mall-plugin#830]
You can see the bug here:
[https://www.larabug.com/exception/YXHEzK9tjzb0XPC](https://www.larabug.com/exception/YXHEzK9tjzb0XPC)

### URL:
https://shop.test/backend/offline/mall/products/create

### Post data
![Codecycler 2021-08-20 at 14 59 57 - Google Chrome](https://user-images.githubusercontent.com/6506510/130236988-cacf592e-889d-4622-b99e-82ca3b3f5a4b.png)

### MySQL version
5.7.32

### October CMS version
2.1.4

### Mall plugin version
dev-develop

**Comment by SebastiaanKloos** [comment]
Debugged it a bit and found out the issue is with the hidden attribute `id` of the `Product` model

**Comment by SebastiaanKloos** [comment]
@tobias-kuendig What do you think? Why is the `id` added to the hidden attributes?

**Comment by tobias-kuendig** [comment]
Ah yes, this was introduced a few days ago:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/fecda49dc904187208404bab575e0542e1ebbd63

Related PR: https://github.com/OFFLINE-GmbH/oc-mall-plugin/pull/815

We added the hidden property in ordner to not leak the whole database schema to the frontend.

This issue is fixed in https://github.com/OFFLINE-GmbH/oc-mall-plugin/commit/26b3736b6b3752c73548b9510d34db95f573c644, thank you for the report!
