### ISSUE TITLE
Free products / set paidState to paid after creating the order

### ISSUE THREAD

**Issue by maartenmachiels** [OFFLINE-GmbH/oc-mall-plugin#847]
Hi,

Besides actual products, the shop I'm building for my client also has free virtual products (like free tickets that only require registration). So it would be possible that a person would checkout an order with a total value of 0.

What I did to accomodate this was to create a new offline payment method named "No payment required", and I modified the paymentselector partial to only show this specific payment method if the current cart total value is 0. This is already pretty good, but in order to have the system send tickets (the file that is connected to the virtual product), I'd like to automatically set the payment status to paid if the order value is 0.

So in my plugins boot method I did the following:

        Event::listen('mall.order.afterCreate', function ($order,$cart) {
            if($order->totalPostTaxes()->price == 0) {
                $order->payment_state = "OFFLINE\Mall\Classes\PaymentState\PaidState";
                $order->save();
            }
        });

But it doesn't work... The order keeps getting the `OFFLINE\Mall\Classes\PaymentState\PendingState` state. Obviously I'm oversimplifying this problem. Could someone please guide me in the right direction or show me the error in my logic?

Thanks in advance and have a great weekend.

**Comment by maartenmachiels** [comment]
Hi, might anyone have a clue how to pursue this?

**Comment by kevinvermeulenn** [comment]
Hi @chocolata, 

Great findings! I would like to have it as well and use it for free whitepapers. Only I don't know exactly where to put the event or to modify the `paymentmethodselector/methods.htm` partial. 

Could you share the locations?

**Comment by chocolata** [comment]
Hi @kevinvermeulenn ,

So you'd need to create a custom plugin for this to work. I don't know if you've done that before, but it's fairly easy. See the documentation here:
[https://docs.octobercms.com/2.x/console/scaffolding.html#create-a-plugin](https://docs.octobercms.com/2.x/console/scaffolding.html#create-a-plugin)

A folder in your plugins folder would be created, along with a file named `Plugin.php`. 
![image](https://user-images.githubusercontent.com/3584586/160245816-76a44588-ce37-471b-83a9-c05b1c4f78b7.png)

In that file, you'd put the snippet in the boot() method. My `Plugin.php` file looks like this:

```
<?php namespace Chocolata\MallEvents;

use OFFLINE\Mall\Models\Order;
use System\Classes\PluginBase;
use System\Classes\PluginManager;
use Event;
use OFFLINE\Mall\Classes\PaymentState\PaidState;

class Plugin extends PluginBase
{
    public $require = ['OFFLINE.Mall','Rainlab.User'];
    public function boot()
    {
        Event::listen('mall.order.afterCreate', function ($order,$cart) {
            // Set the payment state to paid if it's a free product
            if($order->totalPostTaxes()->price == 0) {
                $myOrder = Order::find($order->id);
                $myOrder->payment_state = PaidState::class;
                $myOrder->paid_at = date('Y-m-d H:i:s');
                $myOrder->save();
            }
        });
    }
}
```

Concerning the `paymentmethodselector/methods.htm` partial, just put it in your partials folder in your theme. If you put it there, it should overrule the default partial as set by the OFFLINE.Mall:

![image](https://user-images.githubusercontent.com/3584586/160245868-07c28130-2345-4ffb-8bbd-d0f452baf8f2.png)

If you are stuck, hit me up via the contact form on my website (as listed on my profile), I'd be happy to help you out. I see that we both speak dutch, so that makes it even easier.

Veel succes!
