### ISSUE TITLE
SQLite Support?

### ISSUE THREAD

**Issue by SamBrishes** [OFFLINE-GmbH/oc-mall-plugin#966]
Hello,

I'm currently working on a shop template using your Mall extension and encountered some issues using SQLite for my development (and future demonstration) set-up.

While you mentioned using "MySQL 5.7+ or MariaDB 10.2+" for the best performance, the general support for SQLite seems to struggle. I could fix the missing `JSON_CONTAINS` function issue (on the `OFFLINE\Mall\Classes\Index\MySQL\MySQL` class), and just wanna ask if you even support SQLite at all and / or if you know the current issues with this driver in general? (Of course, I don't wanna run a full functional shop, it would be enough having a demonstration template which does not explode due to some driver issues).

Thanks.

Sincerely,
Sam.

PS.: Off-Topic question: Are you planning a jQuery-free / vanilla JavaScript environment for a future release? The current scripts are not particularly extensive nor deeply bound to jQuery itself, as far as I've seen. Since OC3's Storm JS stuff is now also detached from jQuery, it would be really cool to see as well.

**Comment by tobias-kuendig** [comment]
The performance problems mentioned in the README are really only relevant for large shops. You can also use the file-based JSON index instead of the DB variant.

SQlite is supported in general, but not when using the MySQL index. Either we need to provide a separate driver for SQlite or modify the MySQL index to support SQlite. If it is just a small change go ahead and modify the MySQL index to support the SQlite syntax.

> Off-Topic question: Are you planning a jQuery-free / vanilla JavaScript environment for a future release? 

This would have to be provided by the community (PRs welcome!) as I currently do not have the ressources to implement all these changes myself.

**Comment by SamBrishes** [comment]
This issue has been fixed and released with v3.2.0 / v3.2.1.
