### ISSUE TITLE
Show prices with tax 

### ISSUE THREAD

**Issue by adamo** [OFFLINE-GmbH/oc-mall-plugin#999]
In my client store the prices are imported from a central database and are without tax. 
There's only one tax (VAT) per product (23%). Is there a way to show the price with VAT added store wide or has this to be done by changing every occurrence in the components?

**Comment by Mattia-Marchiorato** [comment]
@adamo Hello!
Because is laravel based and model based you can via API easly "attach" the vat during the import process (or later).
Maybe you can also extend the plugin and create a getter for a price.

Hope this help

**Comment by adamo** [comment]
@Mattia-Marchiorato Thanks for the input. 

I was thinking about the first one and it seems the quickest and least painful.

**Comment by tobias-kuendig** [comment]
Cleaning the data up during the import is certainly the easiest method. Since the VAT can depend on many factors (like the user's origin country), simple tax calculations are only available when the product is in the cart (and therefore is a `CartProduct` model).

On these models, you can use the following accessors:
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/cart/CartItemPriceAccessors.php
